domain:     http://joshtronic.com
email:      joshtronic@gmail.com
future:     true
gravatar:   http://www.gravatar.com/avatar/a8dc1f35af7e04617f9e20d1bb4ced62
markdown:   rdiscount
name_first: Josh
name_full:  Josh Sherman
permalink:  pretty
pygments:   true
