avatar:      http://www.gravatar.com/avatar/a8dc1f35af7e04617f9e20d1bb4ced62
title:       Josh Sherman
description: Hacker, Fiscal Conservative, Tattoos &amp; Expletives
delimiter:   "&nbsp;&nbsp;"
domain:      http://joshtronic.com
email:       joshtronic@gmail.com
markdown:    rdiscount
permalink:   pretty
pygments:    true
username:    joshtronic
future:      false
