avatar:      http://www.gravatar.com/avatar/a8dc1f35af7e04617f9e20d1bb4ced62
title:       Josh Sherman
description: Hacker, Fiscal Conservative, Tattoos &amp; Expletives
delimiter:   "&nbsp;"
markdown:    rdiscount
pygments:    true
username:    joshtronic
